# 单数源配置
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/mydb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root123

# 动态切换数据源-读写分离配置
spring:
  datasource:
    hikari:
      primary:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/mydb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password:
      secondary:
        jdbc-url: jdbc:mysql://127.0.0.1:3316/mydb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password:

# ShardingSphere-读写分离配置
#spring:
#  shardingsphere:
#    props:
#      sql:
#        show: true
#    datasource:
#      names: primary, secondary
#      primary:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        jdbc-url: jdbc:mysql://127.0.0.1:3306/mydb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password:
#      secondary:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        jdbc-url: jdbc:mysql://127.0.0.1:3316/mydb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password:
#    masterslave:
#      name: ms
#      master-data-source-name: primary
#      slave-data-source-names: secondary
logging:
  level:
    root: info
    org.springframework.jdbc.core: debug
