spring:
  datasource:
    driver: org.h2.Driver
    url: jdbc:h2:mem:foo
    username: foo
    password: foo
    hikari:
      maximumPoolSize: 5
      minimumIdle: 5
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000

logging:
  level:
    root: debug
